# Generated by Django 5.2.14 on 2026-05-18 08:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AssignedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('subject', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='published', max_length=20)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_created', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_work', to='core.classsection')),
            ],
            options={
                'ordering': ['due_date', 'subject', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('subject', models.CharField(max_length=80)),
                ('resource_type', models.CharField(choices=[('notes', 'Notes'), ('syllabus', 'Syllabus'), ('assignment_help', 'Assignment Help'), ('reference', 'Reference')], default='notes', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.URLField(blank=True)),
                ('published_on', models.DateField(default=django.utils.timezone.localdate)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_resources', to='core.classsection')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_resources_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_on', 'subject', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AdmitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_name', models.CharField(max_length=120)),
                ('roll_number', models.CharField(max_length=40)),
                ('exam_date', models.DateField()),
                ('reporting_time', models.TimeField()),
                ('venue', models.CharField(max_length=160)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('blocked', 'Blocked')], default='issued', max_length=20)),
                ('issued_on', models.DateField(default=django.utils.timezone.localdate)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admit_cards_issued', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_cards', to='core.student')),
            ],
            options={
                'ordering': ['-exam_date', 'exam_name'],
                'unique_together': {('student', 'exam_name')},
            },
        ),
        migrations.CreateModel(
            name='ResultRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_name', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=80)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('grade', models.CharField(blank=True, max_length=12)),
                ('remarks', models.TextField(blank=True)),
                ('published_on', models.DateField(default=django.utils.timezone.localdate)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_recorded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_records', to='core.student')),
            ],
            options={
                'ordering': ['-published_on', 'exam_name', 'subject'],
                'unique_together': {('student', 'exam_name', 'subject')},
            },
        ),
    ]
