# Generated by Django 5.2.14 on 2026-05-19 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_user_assignedwork_learningresource_admitcard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='capture_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('face_recognition', 'Face Recognition'), ('fingerprint', 'Fingerprint'), ('card_scan', 'Card Scan')], default='manual', max_length=32),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='source_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('device_code', models.CharField(max_length=60, unique=True)),
                ('device_type', models.CharField(choices=[('manual', 'Manual'), ('face_recognition', 'Face Recognition'), ('fingerprint', 'Fingerprint'), ('card_scan', 'Card Scan')], max_length=32)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('provider', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('is_enabled_for_students', models.BooleanField(default=True)),
                ('is_enabled_for_staff', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_devices', to='core.campus')),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_devices_configured', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['campus__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_attendance_records', to='core.attendancedevice'),
        ),
        migrations.CreateModel(
            name='CampusMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('it_admin', 'IT Admin'), ('academic_admin', 'Academic Admin'), ('finance_admin', 'Finance Admin'), ('hr_admin', 'HR Admin'), ('teacher', 'Teacher'), ('support', 'Support')], max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_configure_attendance', models.BooleanField(default=False)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.campus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['campus__name', 'user__username', 'role'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('on_leave', 'On Leave')], default='present', max_length=20)),
                ('capture_method', models.CharField(choices=[('manual', 'Manual'), ('face_recognition', 'Face Recognition'), ('fingerprint', 'Fingerprint'), ('card_scan', 'Card Scan')], default='manual', max_length=32)),
                ('source_reference', models.CharField(blank=True, max_length=120)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance_records', to='core.campus')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_attendance_records', to='core.attendancedevice')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'staff_user__username'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='core.campus')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-created_at'],
                'indexes': [models.Index(fields=['campus', 'status'], name='core_approv_campus__3ff4cb_idx'), models.Index(fields=['entity_type', 'entity_id'], name='core_approv_entity__dbab38_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='attendancedevice',
            index=models.Index(fields=['campus', 'device_type'], name='core_attend_campus__3fd609_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancedevice',
            index=models.Index(fields=['status'], name='core_attend_status_9c3c66_idx'),
        ),
        migrations.AddIndex(
            model_name='campusmembership',
            index=models.Index(fields=['campus', 'role'], name='core_campus_campus__c0ea31_idx'),
        ),
        migrations.AddIndex(
            model_name='campusmembership',
            index=models.Index(fields=['user', 'is_primary'], name='core_campus_user_id_1f6120_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campusmembership',
            unique_together={('campus', 'user', 'role')},
        ),
        migrations.AddIndex(
            model_name='staffattendancerecord',
            index=models.Index(fields=['campus', 'date'], name='core_staffa_campus__fd50df_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendancerecord',
            index=models.Index(fields=['staff_user', 'date'], name='core_staffa_staff_u_40c078_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffattendancerecord',
            unique_together={('staff_user', 'date')},
        ),
    ]
