# Generated by Django 5.2.14 on 2026-06-04 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_school_catalog_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('venue', models.CharField(blank=True, max_length=160)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
            ],
            options={
                'ordering': ['exam_date', 'start_time', 'section__grade_name', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubjectSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('pass_marks', models.DecimalField(decimal_places=2, default=33, max_digits=6)),
                ('weightage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['exam_type__name', 'section__grade_name', 'section__section_name', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('grade_name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['grade_name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Null campus is reserved for global Super Admin announcements.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.campus'),
        ),
        migrations.AddField(
            model_name='document',
            name='staff_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultrecord',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='photo_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='employee_code',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['campus', 'audience', 'is_active'], name='core_announ_campus__93252f_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['staff_user', 'document_type'], name='core_docume_staff_u_4cea31_idx'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='core.campus'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='core.classsection'),
        ),
        migrations.AddField(
            model_name='examsubjectsetup',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subject_setups', to='core.campus'),
        ),
        migrations.AddField(
            model_name='examsubjectsetup',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subject_setups', to='core.classsection'),
        ),
        migrations.AddField(
            model_name='examtype',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='core.campus'),
        ),
        migrations.AddField(
            model_name='examsubjectsetup',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_setups', to='core.examtype'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.examtype'),
        ),
        migrations.AddField(
            model_name='subject',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.campus'),
        ),
        migrations.AddField(
            model_name='examsubjectsetup',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subject_setups', to='core.subject'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='core.subject'),
        ),
        migrations.AddIndex(
            model_name='examtype',
            index=models.Index(fields=['campus', 'is_active'], name='core_examty_campus__1fb2ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examtype',
            unique_together={('campus', 'name')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['campus', 'is_active'], name='core_subjec_campus__73931e_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['campus', 'code'], name='core_subjec_campus__994dce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('campus', 'name', 'grade_name')},
        ),
        migrations.AddIndex(
            model_name='examsubjectsetup',
            index=models.Index(fields=['campus', 'is_active'], name='core_examsu_campus__527350_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examsubjectsetup',
            unique_together={('exam_type', 'section', 'subject')},
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['campus', 'exam_date', 'status'], name='core_examsc_campus__75b77d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together={('section', 'subject', 'exam_date', 'start_time')},
        ),
    ]
