# Generated by Django 5.2.14 on 2026-06-04 21:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_blank_payment_transaction_receipts(apps, schema_editor):
    PaymentTransaction = apps.get_model('core', 'PaymentTransaction')
    for transaction in PaymentTransaction.objects.filter(receipt_number='').only('id', 'receipt_number'):
        transaction.receipt_number = f'legacy-empty-receipt-{transaction.id}'
        transaction.save(update_fields=['receipt_number'])


def legacy_payment_transaction_receipts_to_null(apps, schema_editor):
    PaymentTransaction = apps.get_model('core', 'PaymentTransaction')
    PaymentTransaction.objects.filter(receipt_number__startswith='legacy-empty-receipt-').update(receipt_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_examschedule_examsubjectsetup_examtype_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('due_day', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['campus__name', 'section__grade_name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FinanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('feePaid', 'Fee paid'), ('paymentFailed', 'Payment failed'), ('offlinePaymentAdded', 'Offline payment added'), ('receiptGenerated', 'Receipt generated'), ('salaryPaid', 'Salary paid'), ('feeReminderSent', 'Fee reminder sent')], max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('razorpay', 'Razorpay'), ('upi', 'UPI'), ('card', 'Card'), ('net_banking', 'Net banking'), ('wallet', 'Wallet')], default='razorpay', max_length=32)),
                ('key_id', models.CharField(blank=True, max_length=160)),
                ('key_secret_encrypted', models.TextField(blank=True)),
                ('webhook_secret_encrypted', models.TextField(blank=True)),
                ('upi_id', models.CharField(blank=True, max_length=120)),
                ('allowed_methods', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['campus__name', 'provider'],
            },
        ),
        migrations.CreateModel(
            name='SalarySetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('default_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('default_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['campus__name', 'staff_user__username'],
            },
        ),
        migrations.AddField(
            model_name='feeassignment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='feeassignment',
            name='invoice_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeassignment',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='feeassignment',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeassignment',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='feeassignment',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.campus'),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='payment',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='success', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_pdf_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='webhook_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_records_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='slip_number',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.RunPython(seed_blank_payment_transaction_receipts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.RunPython(legacy_payment_transaction_receipts_to_null, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['campus', 'payment_status'], name='core_paymen_campus__849d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['receipt_number'], name='core_paymen_receipt_f19e07_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='core_paymen_transac_e8c2f7_idx'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='core.campus'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structures_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='core.classsection'),
        ),
        migrations.AddField(
            model_name='feeassignment',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='core.feestructure'),
        ),
        migrations.AddField(
            model_name='financeevent',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_events', to='core.campus'),
        ),
        migrations.AddField(
            model_name='financeevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_events_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateway_configs', to='core.campus'),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_gateway_configs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salarysetup',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_setups', to='core.campus'),
        ),
        migrations.AddField(
            model_name='salarysetup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_setups_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salarysetup',
            name='staff_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_setups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='salary_setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_records', to='core.salarysetup'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['campus', 'is_active'], name='core_feestr_campus__7ac669_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['section', 'is_active'], name='core_feestr_section_ce9199_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('campus', 'section', 'title')},
        ),
        migrations.AddIndex(
            model_name='financeevent',
            index=models.Index(fields=['campus', 'event_type', 'created_at'], name='core_financ_campus__f32176_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentgatewayconfig',
            index=models.Index(fields=['campus', 'provider', 'is_active'], name='core_paymen_campus__bf0e9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentgatewayconfig',
            unique_together={('campus', 'provider')},
        ),
        migrations.AddIndex(
            model_name='salarysetup',
            index=models.Index(fields=['campus', 'is_active'], name='core_salary_campus__5906c0_idx'),
        ),
        migrations.AddIndex(
            model_name='salarysetup',
            index=models.Index(fields=['staff_user', 'is_active'], name='core_salary_staff_u_505998_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salarysetup',
            unique_together={('campus', 'staff_user')},
        ),
    ]
