# Generated by Django 5.2.14 on 2026-06-05 06:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_feestructure_financeevent_paymentgatewayconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedwork',
            name='file_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assignedwork',
            name='file_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='assignedwork',
            name='file_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignedwork',
            name='published_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='file_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='file_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resultrecord',
            name='marks_file_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resultrecord',
            name='marks_file_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='resultrecord',
            name='marks_file_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resultrecord',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resultrecord',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='resultrecord',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('on_duty', 'On Duty')], max_length=20),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='file_url',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('attendanceMarked', 'Attendance marked'), ('notesUploaded', 'Notes uploaded'), ('assignmentPublished', 'Assignment published'), ('assignmentSubmitted', 'Assignment submitted'), ('marksUploaded', 'Marks uploaded'), ('resultPublished', 'Result published'), ('noticePublished', 'Notice published'), ('paymentUpdated', 'Payment updated')], max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_events', to='core.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_events_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_events', to='core.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_events_for_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campus', 'event_type', 'created_at'], name='core_academ_campus__5058e0_idx'), models.Index(fields=['student', 'created_at'], name='core_academ_student_7be08a_idx'), models.Index(fields=['teacher', 'created_at'], name='core_academ_teacher_3806ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_url', models.TextField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=180)),
                ('file_content_type', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('checked', 'Checked')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.assignedwork')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_submissions_checked', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='core.student')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['assignment', 'status'], name='core_assign_assignm_09a883_idx'), models.Index(fields=['student', 'status'], name='core_assign_student_565b61_idx')],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
