# Generated by Django 5.2.14 on 2026-06-05 07:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_assignedwork_file_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicevent',
            name='event_type',
            field=models.CharField(choices=[('attendanceMarked', 'Attendance marked'), ('notesUploaded', 'Notes uploaded'), ('assignmentUploaded', 'Assignment uploaded'), ('assignmentPublished', 'Assignment published'), ('assignmentSubmitted', 'Assignment submitted'), ('marksUploaded', 'Marks uploaded'), ('resultPublished', 'Result published'), ('noticePublished', 'Notice published'), ('paymentUpdated', 'Payment updated'), ('deviceSynced', 'Device synced'), ('schoolStatusChanged', 'School status changed')], max_length=40),
        ),
        migrations.CreateModel(
            name='CommunicationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('provider_name', models.CharField(blank=True, max_length=120)),
                ('sender_id', models.CharField(blank=True, max_length=120)),
                ('api_url', models.URLField(blank=True)),
                ('api_key', models.TextField(blank=True)),
                ('api_secret', models.TextField(blank=True)),
                ('smtp_host', models.CharField(blank=True, max_length=180)),
                ('smtp_port', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('smtp_username', models.CharField(blank=True, max_length=180)),
                ('smtp_password', models.TextField(blank=True)),
                ('whatsapp_phone_number_id', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_settings', to='core.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_settings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['campus__name', 'channel'],
                'indexes': [models.Index(fields=['campus', 'channel', 'is_active'], name='core_commun_campus__32628a_idx')],
                'unique_together': {('campus', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='DeviceSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='success', max_length=20)),
                ('log_type', models.CharField(default='sync', max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sync_logs', to='core.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_sync_logs_created', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='core.attendancedevice')),
            ],
            options={
                'ordering': ['-synced_at'],
                'indexes': [models.Index(fields=['campus', 'status', 'synced_at'], name='core_device_campus__f4dcd1_idx'), models.Index(fields=['device', 'status'], name='core_device_device__6aa10a_idx')],
            },
        ),
    ]
