# Generated by Django 5.2.14 on 2026-06-05 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_academicevent_event_type_communicationsetting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'date'], name='core_attend_student_1db04d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date', 'status'], name='core_attend_date_07f009_idx'),
        ),
        migrations.AddIndex(
            model_name='feeassignment',
            index=models.Index(fields=['student', 'status'], name='core_feeass_student_d03262_idx'),
        ),
        migrations.AddIndex(
            model_name='feeassignment',
            index=models.Index(fields=['due_date', 'status'], name='core_feeass_due_dat_a16f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='feeassignment',
            index=models.Index(fields=['fee_structure', 'status'], name='core_feeass_fee_str_9f54d7_idx'),
        ),
        migrations.AddIndex(
            model_name='feeassignment',
            index=models.Index(fields=['invoice_number'], name='core_feeass_invoice_a17b46_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['due_day', 'is_active'], name='core_feestr_due_day_10b41f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['campus', 'paid_on'], name='core_paymen_campus__eb2f73_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['fee_assignment', 'payment_status'], name='core_paymen_fee_ass_1dfd79_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['campus', 'status', 'created_at'], name='core_paymen_campus__79c02b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['student', 'status'], name='core_paymen_student_0b4d36_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['fee_assignment', 'status'], name='core_paymen_fee_ass_143c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['campus', 'status'], name='core_studen_campus__22d1c2_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['section', 'status'], name='core_studen_section_43d30f_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_number'], name='core_studen_admissi_102036_idx'),
        ),
    ]
