# Generated by Django 5.2.14 on 2026-06-05 14:18

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_attendancerecord_core_attend_student_1db04d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_type', models.CharField(choices=[('full_database', 'Full database'), ('school_data', 'School data'), ('files', 'Files'), ('payment_logs', 'Payment logs'), ('audit_logs', 'Audit logs')], max_length=40)),
                ('frequency', models.CharField(default='daily', max_length=40)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('encryption_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_policies', to='core.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_policies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['campus__name', 'backup_type'],
            },
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_type', models.CharField(choices=[('full_database', 'Full database'), ('school_data', 'School data'), ('files', 'Files'), ('payment_logs', 'Payment logs'), ('audit_logs', 'Audit logs')], max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_jobs', to='core.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_jobs_created', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.backuppolicy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_type', models.CharField(default='download', max_length=40)),
                ('file_name', models.CharField(blank=True, max_length=180)),
                ('granted', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access_logs', to='core.campus')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='core.document')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_access_logs', to='core.student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseUsageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_type', models.CharField(max_length=80)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_usage_metrics', to='core.campus')),
            ],
            options={
                'ordering': ['-period_start', 'campus__name', 'metric_type'],
            },
        ),
        migrations.CreateModel(
            name='QueueJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=5)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_jobs', to='core.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_jobs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'scheduled_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaaSPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('annual_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('custom_pricing_enabled', models.BooleanField(default=False)),
                ('student_limit', models.PositiveIntegerField(default=0, help_text='0 means unlimited.')),
                ('teacher_limit', models.PositiveIntegerField(default=0, help_text='0 means unlimited.')),
                ('storage_limit_mb', models.PositiveIntegerField(default=0, help_text='0 means unlimited.')),
                ('ai_monthly_limit', models.PositiveIntegerField(default=0, help_text='0 means unlimited.')),
                ('whatsapp_monthly_limit', models.PositiveIntegerField(default=0, help_text='0 means unlimited.')),
                ('sms_monthly_limit', models.PositiveIntegerField(default=0, help_text='0 means unlimited.')),
                ('modules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saas_plans_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['monthly_price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('grace', 'Grace'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField()),
                ('grace_period_days', models.PositiveIntegerField(default=7)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('gst_number', models.CharField(blank=True, max_length=40)),
                ('auto_disable_on_expiry', models.BooleanField(default=True)),
                ('last_alert_at', models.DateTimeField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_subscriptions_created', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.saasplan')),
            ],
            options={
                'ordering': ['-end_date', 'campus__name'],
            },
        ),
        migrations.CreateModel(
            name='SecureAPIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('prefix', models.CharField(max_length=16)),
                ('token_hash', models.CharField(max_length=128)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secure_api_tokens', to='core.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secure_api_tokens_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['campus__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=80, unique=True)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='issued', max_length=20)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_url', models.TextField(blank=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_invoices', to='core.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_invoices_created', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.schoolsubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(default='online', max_length=32)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('transaction_id', models.CharField(blank=True, max_length=120)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='success', max_length=20)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='core.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payments_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.subscriptioninvoice')),
            ],
            options={
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('critical', 'Critical')], default='ok', max_length=20)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('metric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='core.campus')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(max_length=80)),
                ('summary', models.CharField(max_length=255)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=12)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_activity_logs', to='core.campus')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhiteLabelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('custom_logo_url', models.TextField(blank=True)),
                ('custom_domain', models.CharField(blank=True, max_length=180)),
                ('primary_color', models.CharField(blank=True, max_length=20)),
                ('secondary_color', models.CharField(blank=True, max_length=20)),
                ('accent_color', models.CharField(blank=True, max_length=20)),
                ('login_heading', models.CharField(blank=True, max_length=160)),
                ('login_subheading', models.CharField(blank=True, max_length=240)),
                ('login_background_url', models.TextField(blank=True)),
                ('email_template_header', models.TextField(blank=True)),
                ('email_template_footer', models.TextField(blank=True)),
                ('report_logo_url', models.TextField(blank=True)),
                ('report_footer', models.TextField(blank=True)),
                ('campus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='white_label_config', to='core.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='white_label_configs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['campus__name'],
            },
        ),
        migrations.AddIndex(
            model_name='backuppolicy',
            index=models.Index(fields=['campus', 'backup_type', 'is_active'], name='core_backup_campus__bd6fd8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='backuppolicy',
            unique_together={('campus', 'backup_type')},
        ),
        migrations.AddIndex(
            model_name='backupjob',
            index=models.Index(fields=['campus', 'backup_type', 'status'], name='core_backup_campus__ca67e8_idx'),
        ),
        migrations.AddIndex(
            model_name='backupjob',
            index=models.Index(fields=['status', 'created_at'], name='core_backup_status_6dbb90_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['campus', 'access_type', 'created_at'], name='core_docume_campus__42bfae_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['document', 'created_at'], name='core_docume_documen_8f71e1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['user', 'created_at'], name='core_docume_user_id_619a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriseusagemetric',
            index=models.Index(fields=['campus', 'metric_type', 'period_start'], name='core_enterp_campus__dd4c1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enterpriseusagemetric',
            unique_together={('campus', 'metric_type', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='queuejob',
            index=models.Index(fields=['status', 'scheduled_at', 'priority'], name='core_queuej_status_a24d19_idx'),
        ),
        migrations.AddIndex(
            model_name='queuejob',
            index=models.Index(fields=['campus', 'job_type', 'status'], name='core_queuej_campus__c4abf4_idx'),
        ),
        migrations.AddIndex(
            model_name='saasplan',
            index=models.Index(fields=['code', 'is_active'], name='core_saaspl_code_7ab464_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolsubscription',
            index=models.Index(fields=['campus', 'status'], name='core_school_campus__7d614b_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolsubscription',
            index=models.Index(fields=['plan', 'status'], name='core_school_plan_id_cb426f_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolsubscription',
            index=models.Index(fields=['end_date', 'status'], name='core_school_end_dat_539ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='secureapitoken',
            index=models.Index(fields=['campus', 'is_active'], name='core_secure_campus__7e4021_idx'),
        ),
        migrations.AddIndex(
            model_name='secureapitoken',
            index=models.Index(fields=['prefix'], name='core_secure_prefix_64fac1_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['campus', 'status', 'due_date'], name='core_subscr_campus__da33ae_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['subscription', 'status'], name='core_subscr_subscri_83be77_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['invoice_number'], name='core_subscr_invoice_96d58f_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['campus', 'payment_status', 'paid_at'], name='core_subscr_campus__e10c10_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['invoice', 'payment_status'], name='core_subscr_invoice_8d8e22_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['transaction_id'], name='core_subscr_transac_cb2679_idx'),
        ),
        migrations.AddIndex(
            model_name='systemhealthsnapshot',
            index=models.Index(fields=['component', 'status', 'checked_at'], name='core_system_compone_0776dc_idx'),
        ),
        migrations.AddIndex(
            model_name='systemhealthsnapshot',
            index=models.Index(fields=['campus', 'component', 'checked_at'], name='core_system_campus__5d1633_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['campus', 'activity_type', 'created_at'], name='core_userac_campus__915835_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', 'created_at'], name='core_userac_user_id_ee37d3_idx'),
        ),
        migrations.AddIndex(
            model_name='whitelabelconfig',
            index=models.Index(fields=['custom_domain'], name='core_whitel_custom__83738d_idx'),
        ),
        migrations.AddIndex(
            model_name='whitelabelconfig',
            index=models.Index(fields=['is_enabled'], name='core_whitel_is_enab_59c43d_idx'),
        ),
    ]
