from django.contrib import admin

from .models import (
    AcademicSession,
    AccountingLedgerEntry,
    AdmitCard,
    AdmissionApplication,
    AdmissionDocument,
    AdmissionFormTemplate,
    Announcement,
    AssetMaintenanceLog,
    AssignedWork,
    ApprovalRequest,
    AttendanceDevice,
    AttendanceRecord,
    AuditEvent,
    BackupJob,
    BackupPolicy,
    Campus,
    CampusMembership,
    ClassSection,
    DeviceLoginSession,
    DocumentAccessLog,
    DigitalLibraryResource,
    EnterpriseUsageMetric,
    ExamSchedule,
    ExamSubjectSetup,
    ExamType,
    FeeAssignment,
    InventoryAsset,
    LibraryBookRequest,
    LearningResource,
    MarketplacePlugin,
    Payment,
    ProductionAuditRun,
    PushNotificationDevice,
    PushNotificationLog,
    QueueJob,
    ReportDefinition,
    ResultRecord,
    SaaSPlan,
    SchoolPluginConfig,
    SchoolSubscription,
    SchoolWebsiteContent,
    SecureAPIToken,
    SecurityEvent,
    SecurityPolicy,
    SubscriptionInvoice,
    SubscriptionPayment,
    SystemHealthSnapshot,
    StaffAttendanceRecord,
    Student,
    Subject,
    SupportTicket,
    TransportDriver,
    TransportTripLog,
    TransportVehicleAttendance,
    UserActivityLog,
    WhiteLabelConfig,
)

admin.site.register(Campus)
admin.site.register(CampusMembership)
admin.site.register(AttendanceDevice)
admin.site.register(AcademicSession)
admin.site.register(ClassSection)
admin.site.register(Subject)
admin.site.register(Student)
admin.site.register(AttendanceRecord)
admin.site.register(StaffAttendanceRecord)
admin.site.register(AssignedWork)
admin.site.register(LearningResource)
admin.site.register(ResultRecord)
admin.site.register(ExamType)
admin.site.register(ExamSubjectSetup)
admin.site.register(ExamSchedule)
admin.site.register(AdmitCard)
admin.site.register(FeeAssignment)
admin.site.register(Payment)
admin.site.register(SaaSPlan)
admin.site.register(SchoolSubscription)
admin.site.register(SubscriptionInvoice)
admin.site.register(SubscriptionPayment)
admin.site.register(WhiteLabelConfig)
admin.site.register(UserActivityLog)
admin.site.register(DocumentAccessLog)
admin.site.register(EnterpriseUsageMetric)
admin.site.register(BackupPolicy)
admin.site.register(BackupJob)
admin.site.register(QueueJob)
admin.site.register(SystemHealthSnapshot)
admin.site.register(SecureAPIToken)
admin.site.register(ApprovalRequest)
admin.site.register(Announcement)
admin.site.register(SupportTicket)
admin.site.register(AuditEvent)
admin.site.register(AdmissionFormTemplate)
admin.site.register(AdmissionApplication)
admin.site.register(AdmissionDocument)
admin.site.register(TransportDriver)
admin.site.register(TransportVehicleAttendance)
admin.site.register(TransportTripLog)
admin.site.register(DigitalLibraryResource)
admin.site.register(LibraryBookRequest)
admin.site.register(InventoryAsset)
admin.site.register(AssetMaintenanceLog)
admin.site.register(SchoolWebsiteContent)
admin.site.register(PushNotificationDevice)
admin.site.register(PushNotificationLog)
admin.site.register(MarketplacePlugin)
admin.site.register(SchoolPluginConfig)
admin.site.register(AccountingLedgerEntry)
admin.site.register(ReportDefinition)
admin.site.register(SecurityPolicy)
admin.site.register(DeviceLoginSession)
admin.site.register(SecurityEvent)
admin.site.register(ProductionAuditRun)
